# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ride_km', models.FloatField()),
                ('ride_avg_km', models.FloatField()),
                ('ride_time', models.FloatField()),
                ('ride_wind', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
