# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biking', '0002_auto_20170312_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeride',
            name='avg_heartbeat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikeride',
            name='kcal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
