# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Product')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
